export const data = [
    {
        id: 201,
        client_id: "b6e1c2c5",
        date_testing: "2018-02-09",
        date_birthdate: "1950-01-01",
        gender: 1,
        ethnicity: 2,
        creatine: 0.59,
        chloride: 92.61,
        fasting_glucose: 84.58,
        potassium: 7.19,
        sodium: 123.26,
        total_calcium: 5.78,
        total_protein: 14.79,
        creatine_unit: "mgdl",
        chloride_unit: "mmoll",
        fasting_glucose_unit: "mgdl",
        potassium_unit: "mmoll",
        sodium_unit: "ul",
        total_calcium_unit: "mgdl",
        total_protein_unit: "gdl"
    },
    {
        id: 202,
        client_id: "b6e1c2c5",
        date_testing: "2018-05-16",
        date_birthdate: "1950-01-01",
        gender: 1,
        ethnicity: 2,
        creatine: 0.82,
        chloride: 92.13,
        fasting_glucose: 75.3,
        potassium: 7.77,
        sodium: 105.67,
        total_calcium: 14.09,
        total_protein: 8.22,
        creatine_unit: "mgdl",
        chloride_unit: "mmoll",
        fasting_glucose_unit: "mgdl",
        potassium_unit: "mmoll",
        sodium_unit: "ul",
        total_calcium_unit: "mgdl",
        total_protein_unit: "gdl"
    },
    {
        id: 203,
        client_id: "b6e1c2c5",
        date_testing: "2018-11-27",
        date_birthdate: "1950-01-01",
        gender: 1,
        ethnicity: 2,
        creatine: 1.26,
        chloride: 82.39,
        fasting_glucose: 93.15,
        potassium: 7.05,
        sodium: 125.38,
        total_calcium: 7.95,
        total_protein: 12.66,
        creatine_unit: "mgdl",
        chloride_unit: "mmoll",
        fasting_glucose_unit: "mgdl",
        potassium_unit: "mmoll",
        sodium_unit: "ul",
        total_calcium_unit: "mgdl",
        total_protein_unit: "gdl"
    },
    {
        id: 204,
        client_id: "b6e1c2c5",
        date_testing: "2019-11-22",
        date_birthdate: "1950-01-01",
        gender: 1,
        ethnicity: 2,
        creatine: 1.14,
        chloride: 87.9,
        fasting_glucose: 90.95,
        potassium: 2.45,
        sodium: 135.61,
        total_calcium: 8.53,
        total_protein: 11.56,
        creatine_unit: "mgdl",
        chloride_unit: "mmoll",
        fasting_glucose_unit: "mgdl",
        potassium_unit: "mmoll",
        sodium_unit: "ul",
        total_calcium_unit: "mgdl",
        total_protein_unit: "gdl"
    },
    {
        id: 205,
        client_id: "b6e1c2c5",
        date_testing: "2019-11-22",
        date_birthdate: "1950-01-01",
        gender: 1,
        ethnicity: 2,
        creatine: 0.52,
        chloride: 93.28,
        fasting_glucose: 63.35,
        potassium: 4.57,
        sodium: 81.19,
        total_calcium: 8.13,
        total_protein: 5.78,
        creatine_unit: "mgdl",
        chloride_unit: "mmoll",
        fasting_glucose_unit: "mgdl",
        potassium_unit: "mmoll",
        sodium_unit: "ul",
        total_calcium_unit: "mgdl",
        total_protein_unit: "gdl"
    },
    {
        id: 206,
        client_id: "b6e1c2c5",
        date_testing: "2021-04-19",
        date_birthdate: "1950-01-01",
        gender: 1,
        ethnicity: 2,
        creatine: 0.83,
        chloride: 97.07,
        fasting_glucose: 63.07,
        potassium: 6.04,
        sodium: 100.5,
        total_calcium: 14.5,
        total_protein: 12.55,
        creatine_unit: "mgdl",
        chloride_unit: "mmoll",
        fasting_glucose_unit: "mgdl",
        potassium_unit: "mmoll",
        sodium_unit: "ul",
        total_calcium_unit: "mgdl",
        total_protein_unit: "gdl"
    },
    {
        id: 207,
        client_id: "b6e1c2c5",
        date_testing: "2021-07-30",
        date_birthdate: "1950-01-01",
        gender: 1,
        ethnicity: 2,
        creatine: 1.06,
        chloride: 105.1,
        fasting_glucose: 115.54,
        potassium: 3.69,
        sodium: 129.22,
        total_calcium: 6.13,
        total_protein: 12.95,
        creatine_unit: "mgdl",
        chloride_unit: "mmoll",
        fasting_glucose_unit: "mgdl",
        potassium_unit: "mmoll",
        sodium_unit: "ul",
        total_calcium_unit: "mgdl",
        total_protein_unit: "gdl"
    },
    {
        id: 208,
        client_id: "b6e1c2c5",
        date_testing: "2021-10-18",
        date_birthdate: "1950-01-01",
        gender: 1,
        ethnicity: 2,
        creatine: 0.49,
        chloride: 95.74,
        fasting_glucose: 60.1,
        potassium: 3.17,
        sodium: 116.46,
        total_calcium: 13.63,
        total_protein: 10.49,
        creatine_unit: "mgdl",
        chloride_unit: "mmoll",
        fasting_glucose_unit: "mgdl",
        potassium_unit: "mmoll",
        sodium_unit: "ul",
        total_calcium_unit: "mgdl",
        total_protein_unit: "gdl"
    },
    {
        id: 209,
        client_id: "b6e1c2c5",
        date_testing: "2022-06-30",
        date_birthdate: "1950-01-01",
        gender: 1,
        ethnicity: 2,
        creatine: 0.66,
        chloride: 94.9,
        fasting_glucose: 131.45,
        potassium: 3.89,
        sodium: 135.31,
        total_calcium: 13.8,
        total_protein: 13.9,
        creatine_unit: "mgdl",
        chloride_unit: "mmoll",
        fasting_glucose_unit: "mgdl",
        potassium_unit: "mmoll",
        sodium_unit: "ul",
        total_calcium_unit: "mgdl",
        total_protein_unit: "gdl"
    },
    {
        id: 210,
        client_id: "b6e1c2c5",
        date_testing: "2022-06-30",
        date_birthdate: "1950-01-01",
        gender: 1,
        ethnicity: 2,
        creatine: 0.3,
        chloride: 80.29,
        fasting_glucose: 141.1,
        potassium: 5.02,
        sodium: 101.15,
        total_calcium: 8.57,
        total_protein: 7.08,
        creatine_unit: "mgdl",
        chloride_unit: "mmoll",
        fasting_glucose_unit: "mgdl",
        potassium_unit: "mmoll",
        sodium_unit: "ul",
        total_calcium_unit: "mgdl",
        total_protein_unit: "gdl"
    }
]